### ISSUE TITLE
当标题中含有中文的时候报错

### ISSUE THREAD

**Issue by alvminvm** [mawenbao/extract_headings#2]
我clone了master并添加了如下内容

```
MD_EXTENSIONS = (['extra', 'codehilite', 'headerid'])
PLUGINS = ['extract_headings']
```

当标题包含中文的时候会报错

```
ERROR: Could not process ./04_test.md
  | 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

但是我看了你的源仓库，文章也是包含中文的，貌似并没有什么问题。
请问这个你是怎么解决的。好像跟u'字符串'之类的有关，因为对这方面不太懂，请指教一下^_^

**Comment by mawenbao** [comment]
我改了python的默认编码

在/usr/lib/python2.7/sitecustomize.py(sitecustomize.py的路径可能因python版本和安装位置而异)加入如下的代码：

```
import sys 
sys.setdefaultencoding("UTF-8")
```

**Comment by alvminvm** [comment]
赞!

**Comment by alvminvm** [comment]
不过这个问题是不是可以通过代码里解决呢？貌似这样是对整个python环境进行设置的吧。  
通过在代码里指定编码格式。

**Comment by alvminvm** [comment]
除了添加

```
MD_EXTENSIONS = (['extra', 'codehilite', 'headerid'])
PLUGINS = ['extract_headings']
```

还要添加什么吗？
现在是标题生成了，但是标题的id没设置上，undefined
所以点目录的时候，无法滚动到指定标题上

**Comment by mawenbao** [comment]
你好，我是这么配置的，或许你可以参考下

``` python
import md5
def my_slugify(value, sep):
    m = md5.md5(value)
    return m.digest().encode('hex')[:6]
MY_SLUGIFY_FUNC = my_slugify
MY_TOC_LIST_TYPE = 'ol'

from markdown.extensions import headerid, codehilite, footnotes
MD_EXTENSIONS = ([
    'extra',
    'footnotes',
    'tables',
    codehilite.CodeHiliteExtension(configs=[('linenums', False), ('guess_lang', False)]),
    headerid.HeaderIdExtension(configs=[('slugify', my_slugify)]),
])
```

**Comment by alvminvm** [comment]
感谢回复。不过我试过了，用了你在github上的配置，唯一有点区别的只是长度不一样而已

```
#m.digest().encode('hex')[:6]
m.digest().encode('hex')
```

现在主要是markdown生成的标题其id没有跟目录的一致，应该说markdown的标题没有生成id

**Comment by mawenbao** [comment]
侧边栏的那个目录是extract_headings插件生成的，正文里标题的id是header_id这个markdown扩展生成的，按说`headerid.HeaderIdExtension(configs=[('slugify', my_slugify)])`配置之后就应该正常了，有报错或warning吗？

**Comment by alvminvm** [comment]
没有报错和warning呢。晚上回去，我跟一下markdown解析的代码吧。
你要是想到什么了可以继续跟我说～～

**Comment by huangfeidian** [comment]
我现在也是同样的问题。。。。。

**Comment by mawenbao** [comment]
'ascii' codec can't encode characters之类的解码问题已经都修复了，请更新插件。（不需要再设置默认编码）

```
git submodule foreach git pull
```

并修改那个slugify函数

```
import md5
def my_slugify(value, sep):
    m = md5.md5(value.encode('UTF-8'))
    return m.digest().encode('hex')[:6]
MY_SLUGIFY_FUNC = my_slugify
MY_TOC_LIST_TYPE = 'ol'
```

**Comment by huangfeidian** [comment]
搞定了，非常感谢。

**Comment by whypro** [comment]
> 侧边栏的那个目录是extract_headings插件生成的，正文里标题的id是header_id这个markdown扩展生成的，按说headerid.HeaderIdExtension(configs=[('slugify', my_slugify)])配置之后就应该正常了，有报错或warning吗？

rst 格式该如何配置呢？生成的 sidebar 是正确的，但是文章内的锚 herf 是 undifined。

**Comment by mawenbao** [comment]
你好，正文里标题的id是markdown的headerid扩展生成的，貌似不支持rst文件呢。。。

**Comment by mawenbao** [comment]
用beautifulsoup重写了下，现在不用headerid来生成文内heading的id了，不过需要安装bs4

```
sudo pip install beautifulsoup4
```

原来的headerid配置也要删掉

```
MD_EXTENSIONS = ([
    headerid.HeaderIdExtension(configs=[('slugify', my_slugify)]),
])
```
